version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data_swagger:/data
    environment:
      - REDIS_PASSWORD=12345678
    command: ["redis-server", "--requirepass", "12345678"]

volumes:
  redis_data_swagger:
    driver: local
